# Configurazione per ambiente di sviluppo
environment: development
debug: true
config_version: "1.0"

model:
  input_size: [128, 128]
  channels: 3
  latent_dim: 512
  architecture: "AutoencoderUNetLite"

training:
  batch_size: 16
  num_epochs: 10
  learning_rate: 0.0001
  validation_split: 0.2
  num_workers: 2
  early_stopping_patience: 5
  gradient_clip_value: 1.0
  save_every_n_epochs: 5

anomaly:
  threshold_pixel: 0.015
  gaussian_sigma: 1.0
  min_recall: 0.95
  use_otsu_threshold: true
  morphological_operations: false
  min_anomaly_area: 10

visualization:
  figure_size: [15, 5]
  dpi: 100
  colormap: "inferno"
  font_size: 10
  save_format: "png"

logging:
  level: "DEBUG"
  console_output: true
  file_output: true
  max_file_size_mb: 50
  backup_count: 3

# I percorsi sono auto-configurati ma possono essere sovrascritti
paths:
  project_root: null    # Auto-detect se non specificato
  data_root: null       # Override se necessario
  output_root: null     # Override se necessario
