# Configurazione per ambiente di produzione
environment: production
debug: false
config_version: "1.0"

model:
  input_size: [128, 128]
  channels: 3
  latent_dim: 512
  architecture: "AutoencoderUNetLite"

training:
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.0001
  validation_split: 0.2
  num_workers: 6
  early_stopping_patience: 15
  gradient_clip_value: 1.0
  save_every_n_epochs: 20

anomaly:
  threshold_pixel: 0.015
  gaussian_sigma: 1.0
  min_recall: 0.95
  use_otsu_threshold: true
  morphological_operations: true
  min_anomaly_area: 15

visualization:
  figure_size: [15, 5]
  dpi: 300
  colormap: "inferno"
  font_size: 12
  save_format: "png"

logging:
  level: "WARNING"
  console_output: false
  file_output: true
  max_file_size_mb: 200
  backup_count: 10

# In produzione, specifica percorsi assoluti per sicurezza
paths:
  # data_root: "/var/lib/anomaly-spotter/data"
  # output_root: "/var/lib/anomaly-spotter/outputs"
  # logs_root: "/var/log/anomaly-spotter"
